#!/usr/bin/env python3
# test_visio_ingestion_preview.py
"""
Functional test for Visio ingestion and preview rendering.
Version: 0.241.078
Implemented in: 0.241.074

This test ensures VSDX files can be parsed into page-level structured content
and rendered as PNG previews for enhanced citation display.
"""

import io
import sys
from pathlib import Path

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = REPO_ROOT / "application" / "single_app"
SAMPLE_VSDX = REPO_ROOT / "artifacts" / "architecture.vsdx"
SAMPLE_SVG = REPO_ROOT / "artifacts" / "architecture.svg"

sys.path.insert(0, str(APP_ROOT))

from functions_visio import build_visio_page_markdown, parse_vsdx_pages, render_vsdx_page_preview


def test_visio_page_parsing():
    """Validate VSDX page extraction from the sample architecture file."""
    assert SAMPLE_VSDX.exists(), f"Sample Visio file not found: {SAMPLE_VSDX}"

    pages = parse_vsdx_pages(str(SAMPLE_VSDX))

    assert len(pages) >= 1
    first_page = pages[0]
    assert first_page["page_number"] == 1
    assert "High level" in first_page["name"]
    assert first_page["width"] > 0
    assert first_page["height"] > 0
    assert len(first_page["shapes"]) > 0
    assert len(first_page["connections"]) >= 0

    markdown = build_visio_page_markdown(SAMPLE_VSDX.name, first_page)
    assert "# Visio page 1: High level" in markdown
    assert "Shape count:" in markdown
    assert any(
        expected_text in markdown
        for expected_text in [
            "Azure Cosmos",
            "Front End Application",
            "Application Gateway",
        ]
    )


def test_visio_preview_rendering():
    """Validate PNG preview rendering for the first Visio page."""
    assert SAMPLE_VSDX.exists(), f"Sample Visio file not found: {SAMPLE_VSDX}"

    png_bytes = render_vsdx_page_preview(str(SAMPLE_VSDX), page_number=1, max_edge_px=1600)

    assert png_bytes.startswith(b"\x89PNG\r\n\x1a\n")
    image = Image.open(io.BytesIO(png_bytes))
    assert image.format == "PNG"
    assert image.width > 100
    assert image.height > 100


def test_visio_reference_geometry_fixture():
    """Validate the sample includes Visio path geometry used by the renderer."""
    assert SAMPLE_VSDX.exists(), f"Sample Visio file not found: {SAMPLE_VSDX}"
    assert SAMPLE_SVG.exists(), f"Sample Visio SVG export not found: {SAMPLE_SVG}"

    pages = parse_vsdx_pages(str(SAMPLE_VSDX))
    geometry_rows = [
        row
        for shape in pages[0]["shapes"]
        for row in shape.get("geometry", [])
    ]
    row_types = {row.get("type") for row in geometry_rows}

    assert "RelMoveTo" in row_types
    assert "RelLineTo" in row_types
    assert "MoveTo" in row_types
    assert "LineTo" in row_types

    svg_text = SAMPLE_SVG.read_text(encoding="utf-8")
    assert "Generated by Microsoft Visio" in svg_text
    assert "<path" in svg_text


def test_visio_preview_master_expansion_is_preview_only():
    """Validate master stencil expansion enriches previews without polluting indexed content."""
    assert SAMPLE_VSDX.exists(), f"Sample Visio file not found: {SAMPLE_VSDX}"

    indexed_pages = parse_vsdx_pages(str(SAMPLE_VSDX))
    preview_pages = parse_vsdx_pages(
        str(SAMPLE_VSDX),
        include_media=True,
        include_master_shapes=True,
    )

    indexed_shapes = indexed_pages[0]["shapes"]
    preview_shapes = preview_pages[0]["shapes"]
    preview_master_shapes = [shape for shape in preview_shapes if shape.get("from_master")]

    assert not any(shape.get("from_master") for shape in indexed_shapes)
    assert len(preview_shapes) > len(indexed_shapes)
    assert len(preview_master_shapes) > 0


def test_visio_preview_master_curve_geometry():
    """Validate preview parsing includes curved master stencil geometry rows."""
    assert SAMPLE_VSDX.exists(), f"Sample Visio file not found: {SAMPLE_VSDX}"

    preview_pages = parse_vsdx_pages(
        str(SAMPLE_VSDX),
        include_media=True,
        include_master_shapes=True,
    )
    preview_row_types = {
        row.get("type")
        for shape in preview_pages[0]["shapes"]
        if shape.get("from_master")
        for row in shape.get("geometry", [])
    }

    assert "RelEllipticalArcTo" in preview_row_types
    assert "RelCubBezTo" in preview_row_types


def run_standalone():
    """Run tests without pytest for local functional validation."""
    tests = [
        test_visio_page_parsing,
        test_visio_preview_rendering,
        test_visio_reference_geometry_fixture,
        test_visio_preview_master_expansion_is_preview_only,
        test_visio_preview_master_curve_geometry,
    ]
    results = []
    for test in tests:
        print(f"Running {test.__name__}...")
        try:
            test()
            print(f"{test.__name__} passed")
            results.append(True)
        except Exception as error:
            print(f"{test.__name__} failed: {error}")
            import traceback
            traceback.print_exc()
            results.append(False)

    print(f"Results: {sum(results)}/{len(results)} tests passed")
    return all(results)


if __name__ == "__main__":
    success = run_standalone()
    sys.exit(0 if success else 1)